### ISSUE TITLE
Crashes when trying to play song (Macos)

### ISSUE THREAD

**Issue by D99-1** [Venipa/ytmdesktop2#87] opened 2023-10-31 07:59 UTC
### Operating system

macos Sonoma 14.1

### YouTube Music Desktop App Version

0.10.11

### Bug description

Crashes when trying to play any song, works after multiple tries of the application crashing then reopening it

### Steps to reproduce

Open app, click on any song

### Relevant log output

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               YouTube Music for Desktop [9115]
Path:                  /Applications/YouTube Music for Desktop.app/Contents/MacOS/YouTube Music for Desktop
Identifier:            net.venipa.ytmdesktop
Version:               0.10.11 (0.10.11)
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-10-31 18:55:08.0364 +1100
OS Version:            macOS 14.1 (23B74)
Report Version:        12
Anonymous UUID:        5BE74807-8990-6891-26EB-FC439D3ED71E

Sleep/Wake UUID:       8C4E1AE8-4C26-4F4F-A2FC-8927EDAC750E

Time Awake Since Boot: 63000 seconds
Time Since Wake:       3099 seconds

System Integrity Protection: enabled

Notes:
PC register does not match crashing frame (0x0 vs 0x7FF807026DDD)

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Codes:       0x0000000000000001, 0x0000000000000018

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [9115]

VM Region Info: 0x18 is not in any region.  Bytes before following region: 140722919931880
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      mapped file              7ffc9ba78000-7ffcc1120000 [598.7M] r-x/r-x SM=COW  ...t_id=dd2edb1f

Error Formulating Crash Report:
PC register does not match crashing frame (0x0 vs 0x7FF807026DDD)

Thread 0 Crashed:: CrBrowserMain Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	    0x7ff807026ddd objc_msgSend + 29
1   CoreFoundation                	    0x7ff80748c0ee -[__NSFrozenDictionaryM objectForKey:] + 77
2   xosms-native.node             	       0x12a1356ef xosms::media_service_get_media_type::h4be8c945c81ce8f3 + 207
3   xosms-native.node             	       0x12a13cb7e neon::types::error::convert_panics::h2ea5d6a31fdeb010 + 78
4   xosms-native.node             	       0x12a138c44 neon::context::internal::Scope$LT$R$GT$::with::h55b55784971cb56b + 180
5   xosms-native.node             	       0x12a138465 _$LT$neon..types..internal..FunctionCallback$LT$T$GT$$u20$as$u20$neon..types..internal..Callback$LT$$BP$mut$u20$neon_runtime..napi..bindings..types..Value__$GT$$GT$::invoke::h0da27bdd63fea7ce + 53
6   Electron Framework            	       0x11c46e6c3 napi_is_detached_arraybuffer + 323
7   Electron Framework            	       0x116e7386a v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) + 12266
8   ???                           	     0x13d1ff10a78 ???
9   ???                           	     0x13d1fe8bb2f ???
10  ???                           	     0x13d1fe97911 ???
11  ???                           	     0x13d1ffab93f ???
12  ???                           	     0x13d1fe8bb2f ???
13  ???                           	     0x13d1fe8bb2f ???
14  ???                           	     0x13d1fe8bb2f ???
15  ???                           	     0x13d1fec2241 ???
16  ???                           	     0x13d1ff65871 ???
17  ???                           	     0x13d1feb2411 ???
18  ???                           	     0x13d1fe89fc7 ???
19  Electron Framework            	       0x116f3ae64 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 6260
20  Electron Framework            	       0x116f3b9c3 v8::internal::Execution::TryCallScript(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::FixedArray>, v8::internal::Execution::MessageHandling, v8::internal::MaybeHandle<v8::internal::Object>*, bool) + 403
21  Electron Framework            	       0x116f3bb30 v8::internal::Execution::TryCall(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*, v8::internal::Execution::MessageHandling, v8::internal::MaybeHandle<v8::internal::Object>*, bool) + 224
22  Electron Framework            	       0x116f67a39 v8::internal::MicrotaskQueue::PerformCheckpointInternal(v8::Isolate*) + 409
23  Electron Framework            	       0x11c404bf0 node::CallbackScope::~CallbackScope() + 1504
24  Electron Framework            	       0x11c405164 node::CallbackScope::~CallbackScope() + 2900
25  Electron Framework            	       0x11c405430 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) + 192
26  Electron Framework            	       0x115eaa73d v8::internal::CallInterfaceDescriptor::IsValidFloatParameterRegister(v8::internal::Register) + 79437
27  Electron Framework            	       0x115df9d6d ElectronInitializeICUandStartNode + 644941
28  Electron Framework            	       0x115de72fd ElectronInitializeICUandStartNode + 568541
29  Electron Framework            	       0x115de7054 ElectronInitializeICUandStartNode + 567860
30  Electron Framework            	       0x115e1c57f v8::CodeEvent::GetCodeSize() + 3999
31  Electron Framework            	       0x1189ea483 node::AsyncResource::get_async_id() const + 6217603
32  Electron Framework            	       0x118f5298d node::AsyncResource::get_async_id() const + 11887757
33  Electron Framework            	       0x118f56c97 node::AsyncResource::get_async_id() const + 11904919
34  Electron Framework            	       0x118f545bd node::AsyncResource::get_async_id() const + 11894973
35  Electron Framework            	       0x11923a6a8 node::AsyncResource::get_async_id() const + 14934440
36  Electron Framework            	       0x118c3f3ad node::AsyncResource::get_async_id() const + 8662701
37  Electron Framework            	       0x118c5e3f4 node::AsyncResource::get_async_id() const + 8789748
38  Electron Framework            	       0x118c9dad6 node::AsyncResource::get_async_id() const + 9049558
39  Electron Framework            	       0x115b5d80a 0x1159ca000 + 1652746
40  Electron Framework            	       0x118c9cb7f node::AsyncResource::get_async_id() const + 9045631
41  CoreFoundation                	    0x7ff8074cba16 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
42  CoreFoundation                	    0x7ff8074cb9b9 __CFRunLoopDoSource0 + 157
43  CoreFoundation                	    0x7ff8074cb788 __CFRunLoopDoSources0 + 215
44  CoreFoundation                	    0x7ff8074ca3f8 __CFRunLoopRun + 919
45  CoreFoundation                	    0x7ff8074c9a99 CFRunLoopRunSpecific + 557
46  HIToolbox                     	    0x7ff8122319d9 RunCurrentEventLoopInMode + 292
47  HIToolbox                     	    0x7ff8122317e6 ReceiveNextEventCommon + 665
48  HIToolbox                     	    0x7ff812231531 _BlockUntilNextEventMatchingListInModeWithFilter + 66
49  AppKit                        	    0x7ff80aa3b885 _DPSNextEvent + 880
50  AppKit                        	    0x7ff80b32f348 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1304
51  AppKit                        	    0x7ff80aa2cdfa -[NSApplication run] + 603
52  Electron Framework            	       0x118c9e8a6 node::AsyncResource::get_async_id() const + 9053094
53  Electron Framework            	       0x118c9c680 node::AsyncResource::get_async_id() const + 9044352
54  Electron Framework            	       0x118c5f187 node::AsyncResource::get_async_id() const + 8793223
55  Electron Framework            	       0x118c24cbf node::AsyncResource::get_async_id() const + 8554431
56  Electron Framework            	       0x117eae262 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 3833106
57  Electron Framework            	       0x117eafb22 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 3839442
58  Electron Framework            	       0x117eabaf4 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 3823012
59  Electron Framework            	       0x116028491 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 15521
60  Electron Framework            	       0x1160296f9 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 20233
61  Electron Framework            	       0x1160291c8 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 18904
62  Electron Framework            	       0x116027f09 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 14105
63  Electron Framework            	       0x116028036 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 14406
64  Electron Framework            	       0x115d5c5a8 ElectronMain + 152
65  dyld                          	       0x204ae73a6 start + 1942
```

**Comment by Penguinify** [comment] 2023-11-09 23:33
I found out that it doesn't crash whenever an advertisement plays.

**Comment by Venipa** [comment] 2023-11-10 01:09
this crash is caused by xosms, will be pushing an update the next days

**Comment by D99-1** [comment] 2023-11-13 10:40
No way! i have struggled with this for so long. I was gonna make a project with the api but decided not to because opening the app was a pain, now i can finally do that and listen to music without having to restart the app 3 times

**Comment by Venipa** [comment] 2024-03-11 13:24
@D99-1 should be fixed with the current release

reopen if not

**Closed by Venipa** 2024-03-11 13:24 UTC
Labels: bug, mac
